### PR TITLE
Issue#28: Better Haiku Example

### PR DESCRIPTION
**Pull request by Real-John-Cheung**
With this new (and still not very complicated) grammar file, the generated haiku now is grammatical in English.
Though, sometimes the result still looks a little bit weird

### CODE REVIEW

**Comment by dhowe** [comment]
please make a separate example for this, so that we don't overwrite the existing

**Comment by Real-John-Cheung** [comment]
@dhowe a new example is made with commit afac09f

**Comment by dhowe** [comment]
Pls test this [closed ticket](https://github.com/dhowe/rita2js/issues/37) by using leading numbers in the haiku. For example, change 'line5' to '5line' and change 'threeSyllableAdj' to '3SylAdj'

**Comment by Real-John-Cheung** [comment]
@dhowe  it works well

**Pull request merged**
